language: node_js
addons:
  firefox: latest
node_js:
- '6'
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
env:
  global:
    - secure: lxyh55KtVo1P6uSWjmidohdDIgBnjUxBSm78hMUghOdDvoe+Nsc2YikNFz6a+oduAkXiQDzuDOXnvAMe5lMJc3KwhzNA33s0lungU4Xb/w6veIXfuQzHIGW3HEV2dKFO/a2vEZJJVSSTLYHv/pz4hke98IBcox0ZcoE7HK+Vmz0WWJU3C4YD82v4ICzijIgJtQPOjTDKZr1odgdXWn1itbEjB70jytqM2g4m3tbCMesr52D90nmwMQRHcaeydw2eaZN1b4nMJQeRAcbtZGEiNlmFKpHB1UXJ4mucit6poNb9WHbC13BRWYOSnc/f9cIqVWl9d7wsrgG2ZR5DIlY0lcPAwZJjOB/dY0WUhzpoZaF8Gvu+9ju6cEoeX8hKGlMu0mrcmigOhTlYPbDr1CAOI1Le8tOO7IQkKPF1yALcGJaKlyPbCQbHP1EKE1SCX+yNQNZtcums15BREMznmi4LkUySTOQHiRj84yETVQHsfdyQrNmDgsPbbJdGDWTFFbFit0bvAnQDeYJ2rGn5w5snpYIllLQ0BMjbJXEenqfdcuB1yZzg8gYTMoyrDf6cHo6YZBHtTtOn5nuL85OzmgQ0D7tmPb+ofdNqporwjZFQc8uArRXTbmfKszfpHaS4fYpdqfZL2++zVfUKDUFTaCIgXcX0lEUq7KRhAFKzwY3Ofto=
    - FIREFOX_BINARY: firefox
